import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`flex min-h-screen flex-col items-center justify-center mx-auto space-y-4 px-24 ${inter.className}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
